/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.1 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2017 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "A1_aliases.h"
#include "A1.h"
#include "A2_aliases.h"
#include "A2.h"
#include "B1_aliases.h"
#include "B1.h"
#include "B2_aliases.h"
#include "B2.h"
#include "UART_1.h"
#include "isr_UART_1_RX.h"
#include "LED_aliases.h"
#include "LED.h"
#include "UART_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

